pipeline {
    agent any

    tools {
        maven "maven"
    }

    stages {
        stage('Build') {
            steps {
                git 'https://github.com/jglick/simple-maven-project-with-tests.git'

                sh "mvn -Dmaven.test.failure.ignore=true clean package"

            }

            
        }
    }
}
